// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU9jlmWOTg27ihEa8xlGEi1xC4nP8eOL4',
    appId: '1:152733126646:web:b03c6aaec82eeba8c201d7',
    messagingSenderId: '152733126646',
    projectId: 'ftracker-baby',
    authDomain: 'ftracker-baby.firebaseapp.com',
    storageBucket: 'ftracker-baby.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8EUoGhUTtq_j1Joe2Y8qmxW7YynB7SBs',
    appId: '1:152733126646:android:ae88ef0debc20ab8c201d7',
    messagingSenderId: '152733126646',
    projectId: 'ftracker-baby',
    storageBucket: 'ftracker-baby.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2fhoG6CIyUfRY7abM6QKf0ulXW-M9HnI',
    appId: '1:152733126646:ios:2965a2ce63bac6fac201d7',
    messagingSenderId: '152733126646',
    projectId: 'ftracker-baby',
    storageBucket: 'ftracker-baby.firebasestorage.app',
    iosBundleId: 'com.example.babyTracker',
  );
}
